version: "3.3"

services:

  node-fetch:
    container_name: "node-fetch"
    image: "ghcr.io/kubero-dev/buildpacks/fetch:main"
    environment:
      - GIT_REPOSITORY=${GIT_REPOSITORY:-git@github.com:kubero-dev/template-nodeapp.git}
      - GIT_BRANCH=${GIT_BRANCH:-main}
      - KUBERO_BUILDPACK_DEFAULT_BUILD_CMD="npm install"
      - KUBERO_BUILDPACK_DEFAULT_RUN_CMD="node index.js"
    volumes:
      - ../../data:/app
      - ../../keys/deploykey:/root/.ssh/deploykey

  node-build:
    container_name: "node-build"
    image: node:latest
    working_dir: /app
    #command: tail -f /dev/null
    command: './init-build.sh'
    volumes:
      - ../../data:/app
    depends_on:
      node-fetch:
        condition: service_completed_successfully


  node-run:
    container_name: "node-run"
    image: node:latest
    working_dir: /app
    #command: tail -f /dev/null
    command: './init-web.sh'
    environment:
      - PORT=9999
    volumes:
      - ../../data:/app:ro
    ports:
      - "8001:9999"
    depends_on:
      node-build:
        condition: service_completed_successfully