version: "3.3"

services:
  static-hugo-fetch:
    container_name: "static-hugo-fetch"
    image: "ghcr.io/kubero-dev/buildpacks/fetch:main"
    environment:
      - GIT_REPOSITORY=${GIT_REPOSITORY:-git@github.com:kubero-dev/template-static-hugo.git}
      - GIT_BRANCH=${GIT_BRANCH:-main}
    volumes:
      - ../../data:/app
      - ../../keys/deploykey:/root/.ssh/deploykey

  static-hugo-build:
    container_name: "static-hugo-build"
    image: klakegg/hugo
    working_dir: /app
    #command: tail -f /dev/null
    command: './init-build.sh'
    volumes:
      - ../../data:/app
    depends_on:
      static-hugo-fetch:
        condition: service_completed_successfully

  static-hugo-run:
    container_name: "static-hugo-run"
    image:  webdevops/nginx:alpine
    working_dir: /app
    #command: tail -f /dev/null
    command: './init-web.sh'
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_DOCUMENT_INDEX=index.html
    volumes:
      - ../../data:/app:ro
    ports:
      - "8005:80"
    depends_on:
      static-hugo-build:
        condition: service_completed_successfully